import Foundation

// MARK: - Configuration

/// Options for Clifford randomized-benchmarking–style sequences.
public struct RandomizedBenchmarkingOptions: Sendable, Equatable {
    /// Register width. Primary analytic path is `1`; `2` is supported for noiseless /
    /// qualitative noisy decay (no tight `p_RB` formula claimed).
    public var qubitCount: Int
    /// Number of random Clifford steps **before** the recovering inverse.
    public var sequenceLength: Int
    /// Target qubit for `qubitCount == 1` sequences.
    public var target: Int

    public init(qubitCount: Int = 1, sequenceLength: Int, target: Int = 0) {
        self.qubitCount = qubitCount
        self.sequenceLength = sequenceLength
        self.target = target
    }
}

public enum RandomizedBenchmarkingError: Error, Equatable, Sendable {
    case invalidQubitCount(Int)
    case invalidSequenceLength(Int)
    case qubitOutOfRange(qubit: Int, qubitCount: Int)
    case emptyCliffordGroup
    case insufficientSamplesForFit
    case nonPositiveDecaySignal
}

// MARK: - Decay / fit

/// Survival (ground-state) probability samples and an exponential fit
/// `P(m) ≈ A · α^m + B`.
public struct RBDecayFit: Sendable, Equatable {
    /// Fitted amplitude `A` in `A·α^m + B`.
    public let amplitude: Double
    /// Decay parameter `α` (`p_RB` in the usual RB notation).
    public let decay: Double
    /// Fitted offset `B`.
    public let offset: Double
    /// Sequence lengths `m` used in the fit.
    public let lengths: [Int]
    /// Measured (or exact) mean survival probabilities `P(m)`.
    public let survivals: [Double]

    /// Standard 1Q form with perfect SPAM: `P(m) = ½ + ½·α^{m+1}` when noise hits
    /// each of the `m` Cliffords **and** the inverse (`m+1` channels).
    public static func idealOneQubitDepolarizing(
        lengths: [Int],
        depolarizingProbability p: Double
    ) -> (survivals: [Double], alpha: Double) {
        let alpha = Self.depolarizingDecayParameter(p: p)
        let survivals = lengths.map { m in
            0.5 + 0.5 * pow(alpha, Double(m + 1))
        }
        return (survivals, alpha)
    }

    /// Bloch / channel factor `α = 1 − 4p/3` for QuantumKit's 1Q depolarizing
    /// `(1-p)ρ + (p/3)Σ_{P∈{X,Y,Z}} PρP` (equivalently `γ = 4p/3` toward `I/2`).
    public static func depolarizingDecayParameter(p: Double) -> Double {
        1.0 - (4.0 * p) / 3.0
    }
}

// MARK: - Public API

/// Clifford randomized-benchmarking–style sequences and survival decay under noise.
///
/// ## Clifford set (n = 1)
/// The **24-element** single-qubit Clifford group (modulo global phase), generated by
/// `H` and `S` and stored as `2×2` unitaries applied via ``Gate/unitary1``. Each RB
/// step is therefore **one** 1Q gate → one global depolarizing application under
/// ``NoiseModel/depolarizingProbability``.
///
/// ## Clifford set (n = 2, optional)
/// Each step draws independent 1Q Cliffords on both qubits and, with probability ½,
/// a ``Gate/cx``. The recovering inverse is the adjoint of the accumulated `4×4`
/// unitary (`customUnitary`). Analytic `p_RB ↔ p` is **not** claimed for n = 2.
///
/// ## Survival metric
/// `P(m) = ⟨0…0|ρ|0…0⟩` after the length-`m` sequence (+ inverse), from exact
/// ``CPUDensityMatrix`` Born probabilities (index `0`, engine LSB). Noiseless
/// circuits should give `P(m) ≈ 1`.
///
/// ## Decay model
/// For n = 1 global depolarizing with parameter `p`, averaging over Cliffords yields
/// approximately
/// `P(m) ≈ ½ + ½ · α^{m+1}` with `α = 1 − 4p/3`
/// (`m` = random steps before inverse; noise also after the inverse).
public enum RandomizedBenchmarking {

    /// Builds a length-`m` random Clifford sequence with recovering inverse so the
    /// ideal unitary is identity (up to global phase).
    public static func makeSequence(
        options: RandomizedBenchmarkingOptions,
        seed: UInt64
    ) throws -> QuantumCircuit {
        guard options.qubitCount == 1 || options.qubitCount == 2 else {
            throw RandomizedBenchmarkingError.invalidQubitCount(options.qubitCount)
        }
        guard options.sequenceLength >= 0 else {
            throw RandomizedBenchmarkingError.invalidSequenceLength(options.sequenceLength)
        }
        guard options.target >= 0, options.target < options.qubitCount else {
            throw RandomizedBenchmarkingError.qubitOutOfRange(
                qubit: options.target,
                qubitCount: options.qubitCount
            )
        }

        var rng = QuantumRNG.seeded(seed)
        if options.qubitCount == 1 {
            return try makeOneQubitSequence(
                length: options.sequenceLength,
                target: options.target,
                rng: &rng
            )
        }
        return try makeTwoQubitSequence(length: options.sequenceLength, rng: &rng)
    }

    /// Exact ground-state survival via CPU density matrix (optional noise).
    public static func survivalProbability(
        circuit: QuantumCircuit,
        noise: NoiseModel? = nil,
        seed: UInt64 = 0
    ) throws -> Double {
        let engine = CPUDensityMatrixEngine()
        let density = try CPUDensityMatrix(qubitCount: circuit.qubitCount)
        var rng = QuantumRNG.seeded(seed)
        _ = try engine.executeRNG(circuit, on: density, rng: &rng, noise: noise)
        return density.probabilitiesDouble()[0]
    }

    /// Mean survival over several seeded sequences of the same length.
    public static func meanSurvival(
        options: RandomizedBenchmarkingOptions,
        noise: NoiseModel?,
        seeds: [UInt64]
    ) throws -> Double {
        guard !seeds.isEmpty else {
            throw RandomizedBenchmarkingError.insufficientSamplesForFit
        }
        var sum = 0.0
        for seed in seeds {
            let circuit = try makeSequence(options: options, seed: seed)
            sum += try survivalProbability(circuit: circuit, noise: noise, seed: seed)
        }
        return sum / Double(seeds.count)
    }

    /// Evaluate mean `P(m)` on a grid of lengths (exact DM).
    public static func survivalCurve(
        qubitCount: Int = 1,
        lengths: [Int],
        noise: NoiseModel?,
        seedsPerLength: [UInt64]
    ) throws -> (lengths: [Int], survivals: [Double]) {
        var survivals: [Double] = []
        survivals.reserveCapacity(lengths.count)
        for m in lengths {
            let options = RandomizedBenchmarkingOptions(
                qubitCount: qubitCount,
                sequenceLength: m
            )
            survivals.append(
                try meanSurvival(options: options, noise: noise, seeds: seedsPerLength)
            )
        }
        return (lengths, survivals)
    }

    /// Fit `P(m) ≈ A·α^m + B` with fixed ideal SPAM `A = B = ½` by regressing
    /// `log(2P − 1) ≈ m·log(α) + c` (uses `α^m` indexing; for the analytic
    /// `α^{m+1}` model compare `decay` to theory after the documented shift).
    ///
    /// Here we fit `2P(m) − 1 ≈ C · α^m` (i.e. absorb the extra `α` into `C`),
    /// so the returned `decay` is still the per-Clifford factor `α = 1 − 4p/3`.
    public static func fitExponentialDecay(
        lengths: [Int],
        survivals: [Double]
    ) throws -> RBDecayFit {
        guard lengths.count == survivals.count, lengths.count >= 2 else {
            throw RandomizedBenchmarkingError.insufficientSamplesForFit
        }

        // y = 2P - 1 ≈ C α^m  →  log y = log C + m log α
        var xs: [Double] = []
        var ys: [Double] = []
        for (m, p) in zip(lengths, survivals) {
            let y = 2.0 * p - 1.0
            guard y > 1e-12 else { continue }
            xs.append(Double(m))
            ys.append(log(y))
        }
        guard xs.count >= 2 else {
            throw RandomizedBenchmarkingError.nonPositiveDecaySignal
        }

        let n = Double(xs.count)
        let sumX = xs.reduce(0, +)
        let sumY = ys.reduce(0, +)
        let sumXX = zip(xs, xs).map(*).reduce(0, +)
        let sumXY = zip(xs, ys).map(*).reduce(0, +)
        let denom = n * sumXX - sumX * sumX
        guard abs(denom) > 1e-18 else {
            throw RandomizedBenchmarkingError.insufficientSamplesForFit
        }
        let slope = (n * sumXY - sumX * sumY) / denom
        let intercept = (sumY - slope * sumX) / n
        let alpha = exp(slope)
        let c = exp(intercept) // C in C·α^m = 2P-1
        // P = ½ + ½·C·α^m  → amplitude = C/2, offset = 1/2
        return RBDecayFit(
            amplitude: 0.5 * c,
            decay: alpha,
            offset: 0.5,
            lengths: lengths,
            survivals: survivals
        )
    }

    /// The 24 single-qubit Clifford unitaries (row-major `2×2`, phase-canonicalized).
    public static var oneQubitCliffordGroup: [[ComplexAmplitude]] {
        Clifford1Q.groupMatrices
    }
}

// MARK: - Sequence builders

private extension RandomizedBenchmarking {

    static func makeOneQubitSequence(
        length: Int,
        target: Int,
        rng: inout QuantumRNG
    ) throws -> QuantumCircuit {
        let group = Clifford1Q.group
        guard !group.isEmpty else { throw RandomizedBenchmarkingError.emptyCliffordGroup }

        var product = C2.identity
        var circuit = try QuantumCircuit(qubitCount: max(target + 1, 1))

        for _ in 0..<length {
            let clifford = group[rng.nextInt(upperBound: group.count)]
            product = clifford.matrix * product
            try circuit.unitary1(matrix: clifford.amplitudes, target: target)
        }

        let inverse = product.adjoint
        try circuit.unitary1(matrix: inverse.amplitudes, target: target)
        return circuit
    }

    static func makeTwoQubitSequence(
        length: Int,
        rng: inout QuantumRNG
    ) throws -> QuantumCircuit {
        let group = Clifford1Q.group
        guard !group.isEmpty else { throw RandomizedBenchmarkingError.emptyCliffordGroup }

        var product = C4.identity
        var circuit = try QuantumCircuit(qubitCount: 2)

        for _ in 0..<length {
            let c0 = group[rng.nextInt(upperBound: group.count)]
            let c1 = group[rng.nextInt(upperBound: group.count)]
            try circuit.unitary1(matrix: c0.amplitudes, target: 0)
            try circuit.unitary1(matrix: c1.amplitudes, target: 1)
            product = C4.tensor(c0.matrix, c1.matrix) * product

            if rng.nextInt(upperBound: 2) == 0 {
                try circuit.cx(0, 1)
                product = C4.cx01 * product
            }
        }

        let inverse = product.adjoint
        try circuit.customUnitary(matrix: inverse.amplitudes, qubits: [0, 1])
        return circuit
    }
}

// MARK: - 1Q Clifford group

private enum Clifford1Q {
    struct Element: Sendable {
        let matrix: C2
        var amplitudes: [ComplexAmplitude] { matrix.amplitudes }
    }

    static let group: [Element] = buildGroup()
    static var groupMatrices: [[ComplexAmplitude]] { group.map(\.amplitudes) }

    private static func buildGroup() -> [Element] {
        let h = C2.h
        let s = C2.s
        var unique: [C2] = []
        var queue: [C2] = [C2.identity]

        func insert(_ m: C2) {
            let canonical = m.phaseCanonicalized()
            if unique.contains(where: { $0.isApproximatelyEqual(to: canonical) }) { return }
            unique.append(canonical)
            queue.append(canonical)
        }

        insert(C2.identity)
        while let current = queue.first {
            queue.removeFirst()
            insert(h * current)
            insert(s * current)
            if unique.count >= 24, queue.isEmpty { break }
            // Cap exploration; group order is 24.
            if unique.count > 48 { break }
        }

        // Keep exactly 24 if we found them; otherwise return what we have.
        return Array(unique.prefix(24)).map { Element(matrix: $0) }
    }
}

// MARK: - 2×2 complex matrices

private struct C2 {
    /// Row-major entries `[a00, a01, a10, a11]`.
    var e: [C64]

    static let identity = C2(e: [.one, .zero, .zero, .one])

    static let h = C2(e: [
        C64(re: 1 / sqrt(2), im: 0),
        C64(re: 1 / sqrt(2), im: 0),
        C64(re: 1 / sqrt(2), im: 0),
        C64(re: -1 / sqrt(2), im: 0)
    ])

    static let s = C2(e: [.one, .zero, .zero, C64(re: 0, im: 1)])

    static func * (lhs: C2, rhs: C2) -> C2 {
        let a = lhs.e, b = rhs.e
        return C2(e: [
            a[0] * b[0] + a[1] * b[2],
            a[0] * b[1] + a[1] * b[3],
            a[2] * b[0] + a[3] * b[2],
            a[2] * b[1] + a[3] * b[3]
        ])
    }

    var adjoint: C2 {
        C2(e: [e[0].conjugate, e[2].conjugate, e[1].conjugate, e[3].conjugate])
    }

    var amplitudes: [ComplexAmplitude] {
        e.map { ComplexAmplitude(real: QFloat($0.re), imaginary: QFloat($0.im)) }
    }

    func phaseCanonicalized() -> C2 {
        guard let pivot = e.first(where: { $0.squaredNorm > 1e-18 }) else {
            return self
        }
        let inv = pivot.unitPhase.conjugate
        return C2(e: e.map { $0 * inv })
    }

    func isApproximatelyEqual(to other: C2, tol: Double = 1e-8) -> Bool {
        for i in 0..<4 {
            if abs(e[i].re - other.e[i].re) > tol || abs(e[i].im - other.e[i].im) > tol {
                return false
            }
        }
        return true
    }
}

// MARK: - 4×4 complex matrices (n = 2 accumulate)

private struct C4 {
    /// Row-major 16 entries.
    var e: [C64]

    static let identity = C4(e: {
        var m = [C64](repeating: .zero, count: 16)
        for i in 0..<4 { m[i * 4 + i] = .one }
        return m
    }())

    /// CX with control 0, target 1 (engine LSB: qubit 0 is LSB).
    /// Basis |q1 q0⟩ with index = q0 + 2*q1? Engine LSB: index bit0 = qubit0, bit1 = qubit1.
    /// CX(0→1): flip qubit1 if qubit0=1.
    /// |00⟩→|00⟩, |01⟩→|11⟩, |10⟩→|10⟩, |11⟩→|01⟩
    /// indices: 0=00, 1=01 (q0=1), 2=10 (q1=1), 3=11
    /// Maps: 0→0, 1→3, 2→2, 3→1
    static let cx01 = C4(e: {
        var m = [C64](repeating: .zero, count: 16)
        let perm = [0, 3, 2, 1]
        for col in 0..<4 {
            m[perm[col] * 4 + col] = .one
        }
        return m
    }())

    static func tensor(_ a: C2, _ b: C2) -> C4 {
        // Kronecker with qubit1 as MSB: b ⊗ a (a on q0, b on q1).
        var m = [C64](repeating: .zero, count: 16)
        for i in 0..<2 {
            for j in 0..<2 {
                for k in 0..<2 {
                    for l in 0..<2 {
                        let row = (i << 1) | k
                        let col = (j << 1) | l
                        m[row * 4 + col] = b.e[i * 2 + j] * a.e[k * 2 + l]
                    }
                }
            }
        }
        return C4(e: m)
    }

    static func * (lhs: C4, rhs: C4) -> C4 {
        var out = [C64](repeating: .zero, count: 16)
        for row in 0..<4 {
            for col in 0..<4 {
                var sum = C64.zero
                for k in 0..<4 {
                    sum = sum + lhs.e[row * 4 + k] * rhs.e[k * 4 + col]
                }
                out[row * 4 + col] = sum
            }
        }
        return C4(e: out)
    }

    var adjoint: C4 {
        var out = [C64](repeating: .zero, count: 16)
        for row in 0..<4 {
            for col in 0..<4 {
                out[col * 4 + row] = e[row * 4 + col].conjugate
            }
        }
        return C4(e: out)
    }

    var amplitudes: [ComplexAmplitude] {
        e.map { ComplexAmplitude(real: QFloat($0.re), imaginary: QFloat($0.im)) }
    }
}

// MARK: - Shared complex scalar

private struct C64: Equatable {
    var re: Double
    var im: Double

    static let zero = C64(re: 0, im: 0)
    static let one = C64(re: 1, im: 0)

    static func + (lhs: C64, rhs: C64) -> C64 {
        C64(re: lhs.re + rhs.re, im: lhs.im + rhs.im)
    }

    static func * (lhs: C64, rhs: C64) -> C64 {
        C64(
            re: lhs.re * rhs.re - lhs.im * rhs.im,
            im: lhs.re * rhs.im + lhs.im * rhs.re
        )
    }

    var conjugate: C64 { C64(re: re, im: -im) }
    var squaredNorm: Double { re * re + im * im }

    var unitPhase: C64 {
        let n = sqrt(squaredNorm)
        if n < 1e-30 { return .one }
        return C64(re: re / n, im: im / n)
    }
}
